import { useState } from "react"
import { Eye, MoreVertical, Receipt, RotateCcw, Search } from "lucide-react"
import { useBusiness } from "../businessContext"
import { Button, PageHeader, Status, cardClass, inputClass } from "../components/BusinessUI"

function Transactions() {
  const { transactions, refund } = useBusiness()
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL"); const [notice, setNotice] = useState("")
  const visible = transactions.filter((item) => (filter === "ALL" || item.status === filter) && `${item.id} ${item.customer} ${item.card} ${item.operatorName}`.toLowerCase().includes(query.toLowerCase()))
  const doRefund = async (item) => { if (window.confirm(`Refund ${item.amount} BP to ${item.customer}?`)) { const ok = await refund(item); setNotice(ok ? `Refund transaction created for ${item.customer}.` : "Refunds are unavailable until the backend is connected.") } }
  const exportCsv = () => { const rows = [["Transaction ID", "Customer", "NFC Card", "Type", "Amount", "Status", "Operator", "Date"], ...visible.map((item) => [item.id, item.customer, item.card, item.type, item.amount, item.status, item.operatorName, item.date])]; const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `buzzTap-transactions-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); setNotice("CSV exported successfully.") }
  return <div className="mx-auto max-w-[1600px]"><PageHeader eyebrow="LEDGER" title="Transactions" description="Business-scoped purchases, wallet loads, and refunds." action={<Button secondary onClick={exportCsv}><Receipt size={17} />Export CSV</Button>} />{notice && <div className="mb-5 rounded-xl border border-[#F5C400]/30 bg-[#F5C400]/10 p-3 text-sm text-[#F5C400]">{notice}</div>}<div className={`${cardClass} mb-6 flex flex-col gap-4 p-4 md:flex-row md:items-center md:justify-between`}><div className="relative w-full md:max-w-md"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#666]" /><input className={`${inputClass} pl-10`} placeholder="Search transaction, customer, card, or operator" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="flex gap-2 overflow-auto">{["ALL", "COMPLETED", "PENDING", "FAILED", "REFUNDED"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold ${filter === item ? "bg-[#F5C400] text-black" : "bg-[#1c1c1c] text-[#777]"}`}>{item}</button>)}</div></div><div className="overflow-hidden rounded-2xl border border-[#222] bg-[#111]"><div className="overflow-x-auto"><table className="w-full min-w-[1020px] text-left"><thead className="border-b border-[#242424] text-xs uppercase tracking-wider text-[#666]"><tr><th className="px-5 py-4">Transaction</th><th className="px-5 py-4">Customer / Card</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Operator</th><th className="px-5 py-4">Date</th><th /></tr></thead><tbody>{visible.map((item) => <tr className="border-b border-[#1d1d1d] last:border-0" key={`${item.id}-${item.type}`}><td className="px-5 py-4 font-medium text-white">{item.id}</td><td className="px-5 py-4"><p className="text-sm text-white">{item.customer}</p><p className="text-xs text-[#666]">{item.card} · {item.workstation}</p></td><td className="px-5 py-4 text-xs text-[#AAA]">{item.type}</td><td className="px-5 py-4 font-semibold text-white">{item.amount.toLocaleString()} BP</td><td className="px-5 py-4"><Status>{item.status}</Status></td><td className="px-5 py-4 text-sm text-white">{item.operatorName}</td><td className="px-5 py-4 text-xs text-[#777]">{item.date}</td><td className="px-5 py-4"><div className="flex gap-1"><button title="View details" className="rounded-lg p-2 text-[#666] hover:bg-[#222] hover:text-white"><Eye size={16} /></button>{item.type === "CUSTOMER_PURCHASE" && item.status === "COMPLETED" && <button title="Refund" onClick={() => doRefund(item)} className="rounded-lg p-2 text-[#666] hover:bg-[#F5C400] hover:text-black"><RotateCcw size={16} /></button>}<button title="More actions" className="rounded-lg p-2 text-[#666] hover:bg-[#222] hover:text-white"><MoreVertical size={16} /></button></div></td></tr>)}</tbody></table></div></div></div>
}
export default Transactions